version: "2"

services:
  rangerdb:
    image: mongo:3.2.10
    volumes:
      - ../../../../data/mongo:/data/db

  ranger:
    build: ./ranger
    # We are passing references to samtools explicitly.
    # Setting REF_CACHE here to catch anything that might leak through.
    environment:
      - REF_CACHE=/tmp/cram_cache/%2s/%2s/%s
    volumes:
      - ../test/server/data:/seqdata:ro # For access for phix bam files
      - ./ranger:/appconf # For access to configuration files
      - ../../../../references:/references:ro
    command: npg_ranger_server -sd -c /appconf/config.json
    entrypoint: /wait-for-it.sh rangerdb:27017 --
    links:
      - rangerdb
    depends_on:
      - rangerdb

  rangerproxy:
    build: ./rangerproxy
    volumes:
      - ../../../../references:/references:ro
    ports:
      - "9090:9090"
    links:
      - ranger

